"""empty message

Revision ID: 1098f07db702
Revises: 5d84586180ce
Create Date: 2018-03-20 20:21:27.339287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1098f07db702'
down_revision = '5d84586180ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('gender', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'gender')
    # ### end Alembic commands ###
